language: c

matrix:
  include:
    - os: linux
      env:
        - HOST="x86_64"
    - os: linux
      env:
        - HOST="i686"

script:
  ci/build.sh ${HOST}

install:
  ci/install.sh



before_deploy:
  - git config --local user.name "Antonino Natale"
  - git config --local user.email "antonio.natale97@hotmail.com"
  - export TRAVIS_TAG=v0.6.$(date +'%Y%m%d')
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: tFGkqzj3VqkVRU6G/3G0oGMIQ8ooOcF2CPMTMHrjYr0sO3WfJXu4T8DJUKuy7+L7oqhveJNFXY5zsIhEf1R6gibTid3yOsBC5XBF1yi6zjkM8CGSnlcV4TG58AMejGJHt1QzKJhYqSELpGkkPolNyI4MDl8SPwiYoDesNo0VmfLXcUsyCZ7PrGCIubsh4WmgWTpVAMS7JHlNWble8jP0Wse3UvRRMIw9FWJ1keeyBxD+Eb7IPDoEKWHAPU9FH2v/By9S4i/QYLm956dgPQKAUx/WdjwCFBCmf96aPVdBv8PYNticIjQxTpyQWSZxPbgOmwgNr/DxuNPVnOHl1wawSdSMChMvp4Crrye26VavFn2DYJcJPiLmFNM0fCcv0sE9KRKliaJ4E/PUeiw7BhLOn9fhoI6lPgrGXYkCcCj1clFdhdEWRCrATsp5SA6IafvvG72DAdUYJdQyUkQzAX4x0tczTIrR+hw2YK/uRKyyPZAA8FBTZOucpvHqxXr8PSDSyuQfEwojUk/iwjLlZOMIPisGWcPZDXlDk5JKofUGqIVcpgmRxiQapTyJRknxjpLzngkbBY8FsxvtXLhWzGBf/6Jh/RJ5F4iyhy0ibpmia8dD4hM0fbNJCxbQnDs/Xme2eB/EM38wdtGKKo+9yDJYnZv1mbrwNRYEjxEn8D5JtIw=
    
  file:
    ${HOST}-aplus-newlib.tar.xz

  skip_cleanup: true
  overwrite: true
  draft: false

  on:
    repo: kwrx/aplus-newlib
    tags: false
